using System.Net.Http.Headers;
using ActivityVocabulary.CoreTypes;
using ActivityVocabulary.Extended.ObjectTypes;

namespace ActivityVocabulary.PropertyTypes;

public record ObjectOrLink(
    CoreTypes.ObjectType? @object = null,
    Link? link = null
);

public record Id() : ObjectOrLink;

public record Type() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Describes an entity that either performed or are expected to perform an
 * activity.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#actor"/>
 * </para>
 * </summary>
 */
public record Actor() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Identifies one or more objects used (or to be used) in the completion of an
 * Activity.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#target"/>
 * </para>
 * </summary>
 */
public record Target() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Identifies one or more objects generated by the activity.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#result"/>
 * </para>
 * </summary>
 */
public record Result() : ObjectOrLink;


/**
 * <summary>
 * <para>
 * Describes an indirect object from which the activity is directed. The precise
 * meaning of the origin is the object of the English preposition "from". For
 * instance, in the activity "John moved an item to List B from List A", the
 * origin of the activity is "List A".
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#origin"/>
 * </para>
 * </summary>
 */
public record Origin() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Identifies an object used (or to be used) in the completion of an activity.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#instrument"/>
 * </para>
 * </summary>
 */
public record Instrument() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Identifies a resource attached or related to an object that potentially
 * requires special handling. The intent is to provide a model that is at least
 * semantically similar to attachments in email.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#attachment"/>
 * </para>
 * </summary>
 */
public record Attachment() : ObjectOrLink;


/**
 * <summary>
 * <para>
 * Identifies an entity to which this object is attributed. The attributed
 * entity might not be an Actor. For instance, an object might be  attributed to
 * the completion of another activity.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#attributedTo"/>
 * </para>
 * </summary>
 */
public record AttributedTo() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Identifies an entity that is part of the total population of entities for
 *  which the object can considered to be relevant.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#audience"/>
 * </para>
 * </summary>
 */
public record Audience() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Identifies the context within which the object exists or an activity was
 * performed.
 * </para><para>
 * The notion of "context" used is intentionally vague. The intended function is
 * to serve as a means of grouping objects and activities that share a common
 * originating context or purpose. An example could be all activities relating
 * to a common project or event.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#context"/>
 * </para>
 * </summary>
 */
public record Context() : ObjectOrLink;

/**
 * <summary>
 * <para>
*  Identifies the entity (e.g. an application) that generated the object.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#generator"/>
 * </para>
 * </summary>
 */
public record Generator() : ObjectOrLink;

/**
 * <summary>
 * Indicates an entity that describes an image an object. Unlike the icon there
 * are no aspect ratio or display size limitations assumed.
 * </summary>
 * <param name="image"></param>
 * <param name="link"></param>
 * <returns></returns>
 */
public record ImageOrLink(
    Image? image = null,
    Link? link = null
);

/**
 * <summary>
 * <para>
 * Indicates an entity that describes an icon for an object. The image should
 * have an aspect ratio of one (horizontal) to one (vertical) and should be
 * suitable for presentation at a small size.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#icon"/>
 * </para>
 * </summary>
 */
public record Icon() : ImageOrLink;

/**
 * <summary>
 * <para>
 * Inndicates one or more entities for which an object is considered a response.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#inreplyto"/>
 * </para>
 * </summary>
 */
public record InReplyTo() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Indicates a physical or logical location.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#location"/>
 * </summary>
 */
public record Location() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Indicates an entity that describes a preview of this object.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#preview"/>
 * </para>
 * </summary>
 */
public record Preview() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * Indicates an entity that describes a related resource. Can be any kind of
 * Object. The key difference between attachment and tag is that the former
 * implies an association by inclusion, while the latter (this) implies an
 * association by reference.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#tag"/>
 * </para>
 * </summary>
 */
public record Tag() : ObjectOrLink;

/**
 * <summary>
 * <para>
 * A direct URL (URI) or a Link to something
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#url"/>
 * </para>
 * </summary>
 * <param name="Url"></param>
 * <param name="Link"></param>
 */
public record UrlOrLink(
    Uri? Url = null,
    Link? Link = null
);

/**
 * <summary>
 * <para>
 * When used on a Link, identifies the MIME media type of the referenced
 * resource.
 * </para><para>
 * When used on an Object, identifies the MIME media type of the value of the
 * content property. If not specified, the content property is assumed to
 * contain text/html content.
 * </para><para>
 * <see href="https://www.w3.org/ns/activitystreams#mediaType"/>
 * </para>
 * </summary>
 * <param name="Value"></param>
 */
public record MediaType(string Value)
{
    public static implicit operator MediaType(string v) => new(v);

    public static implicit operator string(MediaType mt) => mt.Value;
}